services:
  - type: web
    name: arrayindex-website
    env: docker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_EMAILJS_PUBLIC_KEY
        value: iSa7hM9dsxKoq8jYg
      - key: VITE_ADMIN_EMAIL
        sync: false # You'll set this in the Render dashboard
      - key: VITE_ADMIN_PASSWORD
        sync: false # You'll set this in the Render dashboard
    healthCheckPath: /
    autoDeploy: true
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    buildCommand: docker build -t arrayindex-website .
    startCommand: docker run -p 3000:3000 arrayindex-website
    autoDeploy: true
    branch: master 